### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by ramizdemiurge** [offbynull/portmapper#40]
I have this:
`java.io.IOException: Cannot run program "ipconfig": error=2, No such file or directory`

What about linux support? :smiley:

**Comment by offbynull** [comment]
Hey,

This is a commonly reported thing. Linux is supported, but the executables
that get run aren't filtered by operating system. The code will attempt to
run every command regardless of operating system. I chose to do this so
that I could have the widest base of support: Linux, Mac, BSD,
Unix/Linux-like, Windows variants, etc...

In your case, you'll get an error for ipconfig because you're running
Linux. For Windows users, they'll see an error for iFconfig because they're
running Windows.

These errors aren't something you need to worry about. No OS supports all
the commands. You will always see an error for some executable not being
found.
